var images = [
{key: './img/cardinals.png', includes: ['cardinals'], excludes: [], includesOr: ['']},
{key: './img/cardinalsOrCards.png', includes: [''], excludes: [''], includesOr: ['cardinals', 'cards']},
{key: './img/cardinalsOrHashCardinals.png', includes: [''], excludes: [''], includesOr: ['cardinals', '#cardinals']},
{key: './img/cardinalsOrCardsOrHashCardinals.png', includes: [''], excludes: [''], includesOr: ['cardinals', 'cards', '#cardinals']},
{key: './img/cardinalsAndBaseball.png', includes: ['cardinals', 'Baseball'], excludes: [''], includesOr: ['']},
{key: './img/cardinalsOrCardsAndBaseball.png', includes: ['baseball'], excludes: [''], includesOr: ['cardinals', 'cards']},
{key: './img/cardinalsOrHashCardinalsAndBaseball.png', includes: ['baseball'], excludes: [''], includesOr: ['cardinals', '#cardinals']},
{key: './img/cardinalsOrCardsOrHashCardinalsAndBaseball.png', includes: ['baseball'], excludes: [''], includesOr: ['cardinals', 'cards', '#cardinals']},
{key: './img/cardinalsAndBaseballOrMlb.png', includes: ['cardinals'], excludes: [''], includesOr: ['baseball', 'mlb']},
{key: './img/cardinalsOrCardsAndBaseballOrMlb.png', includes: [], excludes: [''], includesOr: ['cardinals', 'cards', 'baseball', 'mlb']},
{key: './img/cardinalsAndMlb.png', includes: ['cardinals', 'mlb'], excludes: [''], includesOr: ['']},
{key: './img/cardinalsAndNotNfl.png', includes: ['cardinals'], excludes: ['NFL'], includesOr: ['']},
{key: './img/cardinalsAndNotFootball.png', includes: ['cardinals'], excludes: ['football'], includesOr: ['']},
{key: './img/cardinalsAndStl.png', includes: ['cardinals', 'stl'], excludes: [''], includesOr: ['']},
{key: './img/cardinalsOrCardsAndStl.png', includes: ['stl'], excludes: [''], includesOr: ['cardinals', 'cards']},
{key: './img/cardinalsOrCardsAndStlAndMlb.png', includes: ['mlb', 'stl'], excludes: [''], includesOr: ['cardinals', 'cards']},
{key: './img/cardinalsAndStlOrStlouis.png', includes: ['cardinals'], excludes: [''], includesOr: ['stl', 'st. louis']},
{key: './img/cardinalsAndStlouis.png', includes: ['cardinals', 'st. louis'], excludes: [''], includesOr: ['']},
{key: './img/cardinalsAndStlouis.png', includes: ['cardinals', 'st louis'], excludes: [''], includesOr: ['']},
{key: './img/cardinalsOrHashCardinalsAndMlb.png', includes: ['mlb'], excludes: [''], includesOr: ['cardinals', '#cardinals']},
{key: './img/cardinalsOrHashCardinalsAndMlbOrBaseball.png', includes: [''], excludes: [''], includesOr: ['cardinals', '#cardinals', 'mlb', 'baseball']},
{key: './img/cardinalsOrHashCardinalsAndMlbOrBaseballAndStl.png', includes: ['Stl'], excludes: [''], includesOr: ['cardinals', '#cardinals', 'mlb', 'baseball']},
{key: './img/cardinalsAndCards.png', includes: ['cardinals', 'cards'], excludes: [], includesOr: ['']},
{key: './img/cardinalsOrCardsAndMlb.png', includes: ['mlb'], excludes: [''], includesOr: ['cardinals', 'cards']},
{key: './img/cardinalsAndBaseballAndMlb.png', includes: ['cardinals', 'Baseball', 'mlb'], excludes: [''], includesOr: ['']},
{key: './img/cardinalsAndNotVikings.png', includes: ['cardinals'], excludes: ['vikings'], includesOr: ['']},
{key: './img/cardinalsAndNotVikingsAndNotNfl.png', includes: ['cardinals'], excludes: ['vikings', 'nfl'], includesOr: ['']},
{key: './img/cardinalsAndBaseballAndStl.png', includes: ['cardinals', 'baseball', 'stl'], excludes: [''], includesOr: ['']},
{key: './img/cardinalsAndBaseballAndStlouis.png', includes: ['cardinals', 'baseball', 'st louis'], excludes: [''], includesOr: ['']},
{key: './img/cardinalsAndBaseballAndStlouis.png', includes: ['cardinals', 'baseball', 'st. louis'], excludes: [''], includesOr: ['']},
{key: './img/cardinalsAndNotNfl.png', includes: ['cardinals', 'baseball'], excludes: ['NFL'], includesOr: ['']},
{key: './img/cardinalsAndNotNfl.png', includes: ['cardinals', 'mlb'], excludes: ['NFL'], includesOr: ['']},
{key: './img/cardinalsAndNotNfl.png', includes: ['cardinals', 'stl'], excludes: ['NFL'], includesOr: ['']},
]


export default images;